!!com.compuware.ispw.wzzms.models.IspwRoot
ispwApplication:
  host: cw09.bmc.com
  port: 46724
  runtimeConfig: tptp
  stream: TOPAZ
  application: HARY
  subAppl: HARY
  sandbox: Y
  pathMappings:
  - path: "**/Sources/Progs"
    types:
    - fileExtension: cbl
      ispwType: COB
    - fileExtension: pli
      ispwType: PLI
  - path: "**/Sources/Subs"
    types:
    - fileExtension: cbl
      ispwType: COB
    - fileExtension: pli
      ispwType: PLI
  - path: "**/Sources/Jobs"
    types:
    - fileExtension: jcl
      ispwType: JOB                        
  - path: "**/Sources/Copys"
    types:
    - fileExtension: cpy
      ispwType: COPY
    - fileExtension: incl
      ispwType: INCL
