on: 
  push:
    branches:
      - main

jobs:
  job_sync:
    runs-on: [self-hosted]
    env:
       Win_Topaz_Location: 'C:\Users\mayajain\CLI261L'
    name: Code Pipeline Sync on self-hosted runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Synchronize
        uses: bmc-compuware/ispw-sync-local@v2.0
        id: sync-local
        with:
          host: 'CW09.bmc.com'
          port: 16196
          uid: ${{ secrets.USER_NAME }}
          pass: ${{ secrets.PWD }}
          runtimeConfiguration: 'TPTP'
          stream: 'TOPAZ'
          application: 'HARY'
          subAppl: 'HARY'
          checkoutLevel: 'FIX'
          gitUid: 'mayajain'
          gitToken: ${{ secrets.TEST }}
          winTopazPath: ${{env.Win_Topaz_Location }}
          ispwConfigPath: "GenApp_MainframeCore/ispwconfig.yml"
          assignmentPrefix: "GFLI"
          showEnv: true
      - name: Generate
        uses: bmc-compuware/ispw-generate@v1
        id: generate
        with:
          ces_url: 'https://cwcc.bmc.com:2020/'
          ces_token: ${{ secrets.CES_TOKEN }}
          srid: 'CCGA'
          runtime_configuration: 'ICCGA'
          generate_automatically: ${{ steps.sync-local.outputs.automaticBuildJson }}
      - name: Get the number of generate failures
        run: echo "The number of generate failures is ${{ steps.generate.outputs.generate_failed_count }}"
